export interface SalesItem {
  id?: string;
  sales_id?: string;
  description: string;
  rate: number;
  quantity: number;
  unit: string;
  currency: 'USD' | 'VND';
  exchange_rate: number;
  tax_percent: number;
  tax_value?: number; // Generated by DB
  total?: number;     // Generated by DB
  created_at?: string;
}

export interface Sales {
  id: string;
  shipment_id: string;
  quote_date?: string;
  no_doc?: string;
  created_at?: string;
  sales_items?: SalesItem[];
}

export interface CreateSalesDto {
  shipment_id: string;
  items: Omit<SalesItem, 'sales_id' | 'tax_value' | 'total' | 'created_at'>[];
}

export type UpdateSalesDto = Partial<CreateSalesDto>;
