export interface SalesItem {
  id?: string;
  sales_id?: string;
  description: string;
  rate: number;
  quantity: number;
  unit: string;
  currency: 'USD' | 'VND';
  exchange_rate: number;
  tax_percent: number;
  tax_value?: number; // Generated by DB
  total?: number;     // Generated by DB
  created_at?: string;
}

export type QuotationStatus = 'draft' | 'confirmed' | 'sent' | 'won' | 'lost' | 'converted' | 'final';
export type QuotationType = 'service_breakdown' | 'option_based';
export type ChargeGroup = 'freight' | 'other' | 'on_behalf';

export interface SalesChargeItem {
  id?: string;
  sales_id?: string;
  charge_group: ChargeGroup;
  freight_code?: string;
  charge_name?: string;
  charge_type?: string;
  currency?: string;
  unit?: string;
  quantity: number;
  unit_price: number;
  vat_percent: number;
  amount_ex_vat?: number;
  vat_amount?: number;
  note?: string;
  display_order?: number;
  created_at?: string;
}

export interface Sales {
  id: string;
  shipment_id?: string | null;
  customer_id?: string | null;
  quote_date?: string;
  no_doc?: string;
  status?: QuotationStatus;
  priority_rank?: number;
  quotation_type?: QuotationType;
  due_date?: string;
  validity_from?: string;
  validity_to?: string;
  sales_person_id?: string;
  customer_trade_name?: string;
  customer_contact_name?: string;
  customer_contact_email?: string;
  customer_contact_tel?: string;
  pol?: string;
  pod?: string;
  pickup?: string;
  final_destination?: string;
  cargo_volume?: string;
  business_team?: string;
  business_department?: string;
  goods?: string;
  transit_time?: string;
  service_mode?: string;
  direction?: string;
  currency_code?: string;
  job_no?: string;
  sales_inquiry_no?: string;
  bill_no?: string;
  customs_declaration_no?: string;
  incoterms?: string;
  notes?: string;
  exchange_rate?: number;
  exchange_rate_date?: string;
  created_at?: string;
  sales_items?: SalesItem[];
  sales_charge_items?: SalesChargeItem[];
}

export interface CreateSalesDto {
  shipment_id?: string | null;
  customer_id?: string | null;
  quote_date?: string | null;
  status?: QuotationStatus;
  priority_rank?: number;
  quotation_type?: QuotationType;
  due_date?: string | null;
  validity_from?: string | null;
  validity_to?: string | null;
  sales_person_id?: string | null;
  customer_trade_name?: string | null;
  customer_contact_name?: string | null;
  customer_contact_email?: string | null;
  customer_contact_tel?: string | null;
  pol?: string | null;
  pod?: string | null;
  pickup?: string | null;
  final_destination?: string | null;
  cargo_volume?: string | null;
  business_team?: string | null;
  business_department?: string | null;
  goods?: string | null;
  transit_time?: string | null;
  service_mode?: string | null;
  direction?: string | null;
  currency_code?: string | null;
  job_no?: string | null;
  sales_inquiry_no?: string | null;
  bill_no?: string | null;
  customs_declaration_no?: string | null;
  incoterms?: string | null;
  notes?: string | null;
  exchange_rate?: number;
  exchange_rate_date?: string | null;
  items: Omit<SalesItem, 'sales_id' | 'tax_value' | 'total' | 'created_at'>[];
  charge_items?: Omit<SalesChargeItem, 'sales_id' | 'amount_ex_vat' | 'vat_amount' | 'created_at'>[];
}

export type UpdateSalesDto = Partial<CreateSalesDto>;
