export interface SalesItem {
  id: string;
  shipment_id: string;
  description: string;
  rate: number;
  quantity: number;
  unit: string;
  currency: 'USD' | 'VND';
  exchange_rate: number;
  tax_percent: number;
  tax_value?: number; // Generated by DB
  total?: number;     // Generated by DB
  created_at?: string;
}

export type CreateSalesItemDto = Omit<SalesItem, 'id' | 'tax_value' | 'total' | 'created_at'>;
export type UpdateSalesItemDto = Partial<CreateSalesItemDto>;
