-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  supplier_id character,
  pic_id uuid,
  no_contract text,
  payment_term text,
  type_logistic boolean DEFAULT false,
  type_trading boolean DEFAULT false,
  file_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT contracts_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT contracts_pic_id_fkey FOREIGN KEY (pic_id) REFERENCES public.employees(id)
);
CREATE TABLE public.customer_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  full_name text NOT NULL,
  position text,
  email text,
  phone text,
  department text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT customer_contacts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.customer_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  created_by uuid,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_notes_pkey PRIMARY KEY (id),
  CONSTRAINT customer_notes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  local_name text,
  english_name text,
  customer_group text,
  customer_source text,
  email text,
  phone text,
  website text,
  address text,
  office_address text,
  bl_address text,
  country text,
  state_province text,
  customer_class text,
  tax_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  code character varying,
  rank smallint DEFAULT 0,
  credit_limit numeric DEFAULT 0,
  credit_term_days integer DEFAULT 0,
  sales_staff text,
  sales_team text,
  sales_department text,
  company_id_number text,
  industry text,
  status character varying NOT NULL DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'follow_up'::character varying, 'quotation_sent'::character varying, 'meeting'::character varying, 'lost'::character varying]::text[])),
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customs_clearances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  hs_code text NOT NULL,
  hs_confirmed boolean NOT NULL DEFAULT false,
  declaration_no text,
  lane_type character varying CHECK (lane_type::text = ANY (ARRAY['green'::character varying, 'yellow'::character varying, 'red'::character varying]::text[])),
  phytosanitary_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (phytosanitary_status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'passed'::character varying, 'failed'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'submitted'::character varying, 'inspecting'::character varying, 'released'::character varying, 'on_hold'::character varying, 'rejected'::character varying]::text[])),
  hold_reason text,
  released_at timestamp with time zone,
  escalated_to_manager boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customs_clearances_pkey PRIMARY KEY (id),
  CONSTRAINT customs_clearances_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.debit_note_chi_ho_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  debit_note_id uuid,
  description text,
  unit text,
  rate numeric,
  quantity numeric,
  amount numeric DEFAULT (rate * quantity),
  sort_order integer DEFAULT 0,
  currency_code character varying DEFAULT 'VND'::character varying,
  exchange_rate numeric DEFAULT 1,
  total numeric DEFAULT ((rate * quantity) * exchange_rate),
  CONSTRAINT debit_note_chi_ho_items_pkey PRIMARY KEY (id),
  CONSTRAINT debit_note_chi_ho_items_debit_note_id_fkey FOREIGN KEY (debit_note_id) REFERENCES public.debit_notes(id)
);
CREATE TABLE public.debit_note_invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  debit_note_id uuid,
  description text,
  unit text,
  rate numeric,
  quantity numeric,
  amount numeric DEFAULT (rate * quantity),
  tax_percent numeric,
  sort_order integer DEFAULT 0,
  currency_code character varying DEFAULT 'VND'::character varying,
  exchange_rate numeric DEFAULT 1,
  total numeric DEFAULT (((rate * quantity) * exchange_rate) * ((1)::numeric + (COALESCE(tax_percent, (0)::numeric) / (100)::numeric))),
  CONSTRAINT debit_note_invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT debit_note_invoice_items_debit_note_id_fkey FOREIGN KEY (debit_note_id) REFERENCES public.debit_notes(id)
);
CREATE TABLE public.debit_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid,
  note_date date DEFAULT CURRENT_DATE,
  no_doc text DEFAULT ('DN-'::text || (shipment_id)::text),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT debit_notes_pkey PRIMARY KEY (id),
  CONSTRAINT debit_notes_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text UNIQUE,
  department text,
  position text,
  phone text,
  address text,
  password text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT employees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.exchange_rates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  currency_code text NOT NULL UNIQUE,
  rate numeric NOT NULL DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT exchange_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_request_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_request_id uuid,
  no_invoice text,
  description text,
  date_issue date,
  payable_amount numeric,
  sort_order integer DEFAULT 0,
  CONSTRAINT payment_request_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT payment_request_invoices_payment_request_id_fkey FOREIGN KEY (payment_request_id) REFERENCES public.payment_requests(id)
);
CREATE TABLE public.payment_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid,
  request_date date DEFAULT CURRENT_DATE,
  no_doc text DEFAULT ('DT-'::text || (shipment_id)::text),
  account_name text,
  account_number text,
  bank_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_requests_pkey PRIMARY KEY (id),
  CONSTRAINT payment_requests_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.purchasing_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid,
  supplier_id character,
  pic_id uuid,
  description text,
  hs_code text,
  rate numeric,
  quantity numeric,
  unit text,
  currency character varying CHECK (currency::text = ANY (ARRAY['USD'::character varying, 'VND'::character varying]::text[])),
  exchange_rate numeric,
  tax_percent numeric,
  tax_value numeric DEFAULT ((((rate * quantity) * exchange_rate) * tax_percent) / (100)::numeric),
  total numeric DEFAULT (((rate * quantity) * exchange_rate) + ((((rate * quantity) * exchange_rate) * tax_percent) / (100)::numeric)),
  specification text,
  note text,
  created_at timestamp with time zone DEFAULT now(),
  created_by_id uuid,
  approved_by_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  CONSTRAINT purchasing_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchasing_items_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT purchasing_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchasing_items_pic_id_fkey FOREIGN KEY (pic_id) REFERENCES public.employees(id),
  CONSTRAINT purchasing_items_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.employees(id),
  CONSTRAINT purchasing_items_approved_by_id_fkey FOREIGN KEY (approved_by_id) REFERENCES public.employees(id)
);
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid,
  quote_date date DEFAULT CURRENT_DATE,
  no_doc text DEFAULT ('Q-'::text || "substring"((id)::text, 1, 8)),
  customer_trade_name text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id)
);
CREATE TABLE public.sales_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  description text,
  rate numeric,
  quantity numeric,
  unit text,
  currency character varying CHECK (currency::text = ANY (ARRAY['USD'::character varying, 'VND'::character varying]::text[])),
  exchange_rate numeric,
  tax_percent numeric,
  tax_value numeric DEFAULT ((((rate * quantity) * exchange_rate) * tax_percent) / (100)::numeric),
  total numeric DEFAULT (((rate * quantity) * exchange_rate) + ((((rate * quantity) * exchange_rate) * tax_percent) / (100)::numeric)),
  created_at timestamp with time zone DEFAULT now(),
  sales_id uuid,
  CONSTRAINT sales_items_pkey PRIMARY KEY (id),
  CONSTRAINT sales_items_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES public.sales(id)
);
CREATE TABLE public.shipment_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shipment_id uuid NOT NULL,
  doc_type character varying NOT NULL CHECK (doc_type::text = ANY (ARRAY['commercial_invoice'::character varying, 'packing_list'::character varying, 'sales_contract'::character varying, 'co_form_e'::character varying, 'phytosanitary'::character varying, 'bill_of_lading'::character varying, 'import_document'::character varying]::text[])),
  doc_number text,
  version integer NOT NULL DEFAULT 1,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'verified'::character varying, 'rejected'::character varying, 'issued'::character varying]::text[])),
  file_url text,
  issued_at date,
  verified_at timestamp with time zone,
  verified_by_id uuid,
  note text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT shipment_documents_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_documents_shipment_id_fkey FOREIGN KEY (shipment_id) REFERENCES public.shipments(id),
  CONSTRAINT shipment_documents_verified_by_id_fkey FOREIGN KEY (verified_by_id) REFERENCES public.employees(id)
);
CREATE TABLE public.shipments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid,
  supplier_id character,
  commodity text,
  hs_code text,
  quantity numeric,
  packing text,
  vessel_voyage text,
  term text,
  transport_air boolean DEFAULT false,
  transport_sea boolean DEFAULT false,
  load_fcl boolean DEFAULT false,
  load_lcl boolean DEFAULT false,
  pol text,
  pod text,
  etd date,
  eta date,
  created_at timestamp with time zone DEFAULT now(),
  pic_id uuid,
  code text,
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'feasibility_checked'::character varying, 'planned'::character varying, 'docs_ready'::character varying, 'booked'::character varying, 'customs_ready'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'cost_closed'::character varying, 'cancelled'::character varying]::text[])),
  is_docs_ready boolean NOT NULL DEFAULT false,
  is_hs_confirmed boolean NOT NULL DEFAULT false,
  is_phytosanitary_ready boolean NOT NULL DEFAULT false,
  is_cost_locked boolean NOT NULL DEFAULT false,
  is_truck_booked boolean NOT NULL DEFAULT false,
  is_agent_booked boolean NOT NULL DEFAULT false,
  pod_confirmed_at timestamp with time zone,
  cost_locked_at timestamp with time zone,
  shipment_ready_to_run boolean DEFAULT (is_docs_ready AND is_hs_confirmed AND is_phytosanitary_ready AND is_cost_locked AND is_truck_booked AND is_agent_booked),
  pickup_date date,
  delivery_date date,
  yard_dropoff_date date,
  yard_pickup_date date,
  customs_declaration_no text,
  bill_no text,
  container_no text,
  truck_plate_no text,
  driver_name text,
  extra_yard_cost numeric NOT NULL DEFAULT 0,
  extra_trip_cost numeric NOT NULL DEFAULT 0,
  note text,
  CONSTRAINT shipments_pkey PRIMARY KEY (id),
  CONSTRAINT shipments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT shipments_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT shipments_pic_id_fkey FOREIGN KEY (pic_id) REFERENCES public.employees(id)
);
CREATE TABLE public.suppliers (
  id character NOT NULL,
  company_name text NOT NULL,
  email text,
  phone text,
  address text,
  tax_code text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  representative text,
  tax_code text,
  address text,
  logo_url text,
  phone text,
  email text,
  website text,
  facebook text,
  community_group text,
  zalo text,
  tiktok text,
  tech_support_name text,
  tech_support_role text,
  tech_support_phone text,
  tech_support_email text,
  business_support_name text,
  business_support_role text,
  business_support_phone text,
  business_support_email text,
  version text DEFAULT '2.4.0'::text,
  license_date date DEFAULT '2024-01-01'::date,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);