export interface PurchasingItem {
  id: string;
  shipment_id: string;
  supplier_id: string;
  pic_id?: string | null;
  created_by_id?: string | null;
  approved_by_id?: string | null;
  status?: 'pending' | 'approved' | 'rejected' | null;
  description: string;
  hs_code?: string | null;
  rate: number;
  quantity: number;
  unit: string;
  currency: string;
  exchange_rate: number;
  tax_percent: number;
  tax_value?: number; // Generated by DB
  total?: number;     // Generated by DB
  specification?: string | null;
  note?: string | null;
  created_at?: string;
}

export type CreatePurchasingItemDto = Omit<PurchasingItem, 'id' | 'tax_value' | 'total' | 'created_at'>;
export type UpdatePurchasingItemDto = Partial<CreatePurchasingItemDto>;
